apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: raihanorium
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: raihanorium/kubernetes-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
