apiVersion: v1
kind: Service
metadata:
  namespace: raihanorium
  name: web-service
  labels:
    app: web-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 8090
      targetPort: 80
      nodePort: 30080